### ISSUE TITLE
Custom resolutions or scaling (other than provided by xrandr 1.2)

### ISSUE THREAD

**Issue by carlinux** [FeralInteractive/ferallinuxscripts#11]
Hi,
Usually, in order to make a game run smoothly, we have to reduce the resolution. This is specially necessary in monitors with 21:9 1440p or 4k Res.  
Some of us have monitors with bad EDID with only one resolution available.
Since games like Feral's Hitman (i'm not sure the rest)  scale the resolution rather than forcing a desktop change would necessary to be able to select other resolutions appart from the xrandr 1.2, like VESA standard or xrandr 1.1 resolutions. 

I think it would be good to change the behaviour of the launcher in this cases and make it offer more resolutions. 
In my case i only have 3440x1440 (X34 Predator)  available and i have to lower the quality of the game just to barely be able to play it. 

I'm sorry if this issue doesn't belong here so, please, point me the right place to open the issue then. 

Thanks in advance (and thanks for good Work!)

**Comment by jwyatt-feral** [comment]
Thanks!

Unfortunately this is a little outside of the scope of the scope of this tracker - it doesn't seem like this is an issue with the launch scripts, but rather a feature request for these games? As such I'll close this for now.

Please do get in touch with support@feralinteractive.com - they can log feature requests and bugs for future releases, and may be able to help with workarounds.

**Comment by carlinux** [comment]
ok then, I'll write them with this issue.
Thanks
