### ISSUE TITLE
"Deus Ex: Mankind Divided" crashes when starting on Arch Linux

### ISSUE THREAD

**Issue by nning** [FeralInteractive/ferallinuxscripts#4]
Hey,

when I try starting "Deus Ex: Mankind Divided" on Arch Linux, it crashes right away.

    ./bin/DeusExMD: /usr/lib/libldap_r-2.4.so.2: no version information available (required by ./bin/../lib/x86_64/libcurl.so.4)
    ./bin/DeusExMD: /usr/lib/liblber-2.4.so.2: no version information available (required by ./bin/../lib/x86_64/libcurl.so.4)

(I removed the absolute paths to the `DeusExMD` binary and libs from the logs.)

So it seems, `libcurl` is shipped (connected to #2?) but depends on system libraries from `openldap`. Both `libldap_r`, and `liblber` are provided by the [`libldap` package](https://www.archlinux.org/packages/core/x86_64/libldap/) in version 2.4.44-5. Ubuntu 17.04 also includes `libldap` 2.4.44 but seemingly does not have this problem?

If I move `./lib/x86_64/libcurl.so.4`, `DeusExMD` uses my system's `libcurl` (as shown by `ldd`) but also crashes right away. In this case no errors are logged (when steam is started from terminal).

Let me know, if you need any additional information!

Thanks very much and best regards,
henning

#### System Info

AMD Athlon(tm) II X4 630 Processor (x86_64)
Radeon HD 7870

linux 4.12.8-2
xf86-video-ati 1:7.9.0-2
mesa 17.1.6-1
steam 1.0.0.54-1
steam-native-runtime 1.0.0.54-3

**Comment by mdiluz** [comment]
Hi @nning, Those two version warnings can be harmless unfortunately, so don't directly indicate a problem.

This sounds like an issue that support would be best suited to deal with, could you contact [support@feralinteractive.com](support@feralinteractive.com) with these details and any crash logs that were generated? I'll pass this on so support know to expect you.

I'll close this off if we manage to work out the issue.

**Comment by nning** [comment]
Support already sent me here... ;-)

**Comment by mdiluz** [comment]
Ah, my bad. Apologies for the mixup. I've asked them to re-open your ticket.

**Comment by mdiluz** [comment]
Closing as this is being dealt with by Support

**Comment by nning** [comment]
Thanks!
