### ISSUE TITLE
TW Warhammer libicui18n.so.51: cannot open shared object file [tumbleweed]

### ISSUE THREAD

**Issue by moozaad** [FeralInteractive/ferallinuxscripts#5]
New issue with clean install of  TW:WH
```
.local/share/Steam/steamapps/common/Total War WARHAMMER/bin/TotalWarhammer: error while loading shared libraries: libicui18n.so.51: cannot open shared object file: No such file or directory
```

added to after gameroot decl (line 10) of TotalWarhammer.sh
```
LD_LIBRARY_PATH="${GAMEROOT}/lib/x86_64:${LD_LIBRARY_PATH}"
```

Cleared out the old libcurl and it was able to run again. #2

**Comment by mdiluz** [comment]
Hi @moozaad,

Looks a combination of #2 and #3, is that fair to say?

**Comment by moozaad** [comment]
#2 is still obviously an issue but is separate. This is specifically a broken library path, which I can see an [example](https://github.com/FeralInteractive/ferallinuxscripts/issues/3#issuecomment-324136895) of in #3 mixed in with a couple of other issues.

Has something changed recently so that `FERAL_LIB_PATH="lib/x86_64"` has been removed from LD_LIBRARY_PATH in the last few months?

**Comment by mdiluz** [comment]
Yeah, that broken library path is #3 unfortunately. Testing on my Tumbleweed it looks like they haven't yet merged the needed upstream [fix](https://sourceware.org/git/gitweb.cgi?p=glibc.git;h=45ff34638f034877b6a490c217d6a0632ce263f4). Hopefully that happens soon.

`FERAL_LIB_PATH` was only ever used for preloading some specific libraries, not for assisting the dynamic linker in finding where our multilib libraries were.

**Comment by esmithferal** [comment]
Closing issue as this appears to have been long since resolved due to upstream fixes. Feel free to reopen with new details if it has returned in current releases.
